name: kyll-thrill
markdown: redcarpet
highlighter: pygments
port: 4001
title: kyll-thrill
permalink: "/blog/:year/:month/:day/:title"
exclude: [node_modules]
# You might want to change this if you are running on another base URL.
baseurl: /kyll-thrill

# Used for the RSS feed. Edit to suit your needs.
description: Kyll-thrill. Mithril.js + jekyll.
url: https://eiriksm.github.io/kyll-thrill

# Use this for google analytics.
ga_id: UA-49256770-1

# Use this for disqus
disqus_shortname: kyllthrill

# Select a theme. Default: 'thrill'
theme: thrill

# Prose.io support. If you want to have an editor for your blog, this is a
# simple solution.
prose:
  rooturl: "_posts"
  media: 'media'
  ignore:
    - _config.yml
    - /_layouts
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
